# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: monsters.fun
networks:
- id: 11124
  start_block: 8963740
  rpc_config: 
    url: https://api.testnet.abs.xyz  
  contracts:
  - name: CreatureBoringFactory
    address:
    - 0xd96623b95abf7acc754642bc0e057afe302832e8
    handler: src/EventHandlers.ts
    events:
    - event: event TokenCreated(address tokenAddress, string name, string symbol)
  - name: CreatureBoringToken    
    handler: src/EventHandlers.ts
    events:
    - event: BattleStarted(address indexed opponent)
    - event: BattleEnded(address indexed winner, address indexed loser, uint256 transferredValue)
      field_selection:  
        transaction_fields: 
        - "hash"   
    - event: Trade(address indexed trader, bool isBuy, uint256 amount, uint256 ethAmount, uint256 protocolFee)
      field_selection:  
        transaction_fields: 
        - "hash"         
    - event: Transfer(address indexed from, address indexed to, uint256 value)
      field_selection:  
        transaction_fields: 
        - "hash"         
    - event: PriceUpdate(uint256 newPrice, uint256 tokenSupply, uint256 curveMultiplierValue)
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: Paused(address account)
    - event: Unpaused(address account)
# raw_events: true
    # - event: Approval(address indexed owner, address indexed spender, uint256 value)
    # - event: TokensMigrated(address indexed account, uint256 amount)
    # - event: WhitelistPurchase(address indexed buyer, uint256 amount)
